import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Cursor from "@/components/Cursor";
import Navigation from "@/components/Navigation";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased selection:bg-black selection:text-white`}>
      <body className="relative bg-[var(--background)] text-[var(--foreground)] min-h-screen font-sans selection:bg-[var(--foreground)] selection:text-[var(--background)]">
        <Cursor />
        <Navigation />
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
